[FIX] java.lang.OutOfMemoryError: Java heap space in postgres-jmap-integration-tests
Hopefully, this can fix timeout builds (because of OOM) recently.

[INFO] ---------< com.linagora.tmail:postgres-jmap-integration-tests >---------
[INFO] Building Twake Mail :: Integration Tests :: JMAP :: Postgres 1.0.0-SNAPSHOT [67/84]
[INFO]   from integration-tests/jmap/postgres-jmap-integration-tests/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- surefire:3.5.3:test (default-cli) @ postgres-jmap-integration-tests ---
...

07:00:12.022 [ERROR] r.c.s.Schedulers - Scheduler worker in group main failed with an uncaught exception

java.lang.OutOfMemoryError: Java heap space