ISSUE-1198 Add docs for disable S3 metrics
Otherwise, we have metrics key conflict between 2 blob stores:
09:00:22.679 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/blob.properties
09:00:22.899 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
java.lang.IllegalArgumentException: A metric named s3_httpClient_availableConcurrency already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:168)
	at org.apache.james.metrics.dropwizard.DropWizardGaugeRegistry.settableGauge(DropWizardGaugeRegistry.java:53)
	at org.apache.james.blob.objectstorage.aws.JamesS3MetricPublisher.<init>(JamesS3MetricPublisher.java:45)
	at org.apache.james.blob.objectstorage.aws.S3ClientFactory.lambda$new$0(S3ClientFactory.java:92)