[FIX] Demo: Update ai bot jar
Fix the following error when running demo:
```
  09:10:19.327 [WARN ] r.c.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.AbstractMethodError: Receiver class com.linagora.tmail.jmap.aibot.AiBotCapabilityFactory$ does not define or inherit an implementation of the resolved method 'abstract org.apache.james.jmap.core.Capability create(org.apache.james.jmap.core.UrlPrefixes, org.apache.james.core.Username)' of interface org.apache.james.jmap.core.CapabilityFactory.
```